CREATE OR REPLACE PROCEDURE ACTUALIZAR_TRABAJADOR 
(
vNOMBRE IN TRABAJADOR.NOMBRE%TYPE,
vAPELLIDO1 IN TRABAJADOR.APELLIDO1%TYPE,
vAPELLIDO2 IN TRABAJADOR.APELLIDO2%TYPE,
vDIRECCION IN TRABAJADOR.DIRECCION%TYPE,
vTEL_EMP IN TRABAJADOR.TEL_EMP%TYPE,
vTEL_PER IN TRABAJADOR.TEL_PER%TYPE,
vSALARIO IN TRABAJADOR.SALARIO%TYPE,
vFECHA_NAC IN TRABAJADOR.FECHA_NAC%TYPE,
vDNI IN TRABAJADOR.DNI%TYPE
)
IS
  BEGIN
  UPDATE TRABAJADOR SET NOMBRE=vNOMBRE,APELLIDO1=vAPELLIDO1,
  APELLIDO2=vAPELLIDO2,DIRECCION=vDIRECCION, TEL_EMP=vTEL_EMP,
  TEL_PER=vTEL_PER,SALARIO=vSALARIO,FECHA_NAC=vFECHA_NAC
  WHERE DNI=VDNI;
  END;
