CREATE OR REPLACE PACKAGE GESTIONAR_PARTES
IS
  --Declaración del paquete
  
TYPE CURSOR_PARTES IS REF CURSOR;
  
  PROCEDURE VISUALIZAR_LISTA_PARTES(C_PARTES OUT CURSOR_PARTES);
  PROCEDURE VISUALIZAR_PARTE_ID (P_ID IN NUMBER, PDATO_ID OUT NUMBER);
  PROCEDURE VISUALIZAR_PARTE_FECHA(P_FECHA IN DATE, PDATO_FECHA OUT DATE);
  
END;