CREATE OR REPLACE PACKAGE GESTIONAR_CENTRO
IS
  --Declaración del paquete
TYPE CURSOR_CENTROS is ref cursor;

  PROCEDURE VISUALIZAR_LISTA_CENTRO(C_CENTROS OUT CURSOR_CENTROS);
  PROCEDURE VISUALIZAR_DATOS_CENTRO_ID(P_ID IN NUMBER,PDATOS_CENTRO OUT VARCHAR2, PNUM_TRABAJADORES OUT NUMBER);
  PROCEDURE VISUALIZAR_DATOS_CENTRO_NOMBRE(P_NOMBRE IN VARCHAR2, PDATOS_CENTRO OUT VARCHAR2,PNUM_TRABAJADORES OUT NUMBER);
  PROCEDURE INSERTAR_DATOS_CENTRO(NOMBRE IN CENTRO.NOMBRE%TYPE, DIRECCION IN CENTRO.DIRECCION%TYPE, TELEFONO IN CENTRO.TELEFONO%TYPE);
  PROCEDURE ACTUALIZAR_DATOS_CENTRO(vNOMBRE IN CENTRO.NOMBRE%TYPE, vDIRECCION IN CENTRO.DIRECCION%TYPE, vTELEFONO IN CENTRO.TELEFONO%TYPE, vCODIGO IN CENTRO.CODIGO%TYPE);

END;