CREATE OR REPLACE PROCEDURE INSERTAR_TRABAJADOR 
(vDNI IN TRABAJADOR.DNI%TYPE,
vNOMBRE IN TRABAJADOR.NOMBRE%TYPE,
vAPELLIDO1 IN TRABAJADOR.APELLIDO1%TYPE,
vAPELLIDO2 IN TRABAJADOR.APELLIDO2%TYPE,
vDIRECCION IN TRABAJADOR.DIRECCION%TYPE,
vTEL_EMP IN TRABAJADOR.TEL_EMP%TYPE,
vTEL_PER IN TRABAJADOR.TEL_PER%TYPE,
vSALARIO IN TRABAJADOR.SALARIO%TYPE,
vFECHA_NAC IN TRABAJADOR.FECHA_NAC%TYPE,
vTIPO IN TRABAJADOR.TIPO%TYPE,
vCENTRO IN TRABAJADOR.CENTRO%TYPE
)
IS
  BEGIN
  INSERT INTO TRABAJADOR VALUES(vDNI,vNOMBRE,vAPELLIDO1,vAPELLIDO2,vDIRECCION,
  vTEL_EMP, vTEL_PER, vSALARIO, vFECHA_NAC, vTIPO, vCENTRO);
  END;
