CREATE OR REPLACE PROCEDURE LECTURA_TRABAJADORES_DNI
(vDNI IN TRABAJADOR.DNI%TYPE,
vNOMBRE OUT TRABAJADOR.NOMBRE%TYPE,
vAPELLIDO1 OUT TRABAJADOR.APELLIDO1%TYPE,
vAPELLIDO2 OUT TRABAJADOR.APELLIDO2%TYPE,
vDIRECCION OUT TRABAJADOR.DIRECCION%TYPE,
vTEL_EMP OUT TRABAJADOR.TEL_EMP%TYPE,
vTEL_PER OUT TRABAJADOR.TEL_PER%TYPE,
vSALARIO OUT TRABAJADOR.SALARIO%TYPE,
vFECHA_NAC OUT TRABAJADOR.FECHA_NAC%TYPE,
vCENTRO OUT TRABAJADOR.CENTRO%TYPE
)
IS  
BEGIN 
  SELECT NOMBRE,APELLIDO1,APELLIDO2,DIRECCION,TEL_EMP,TEL_PER,SALARIO,FECHA_NAC,CENTRO
  INTO vNOMBRE,vAPELLIDO1,vAPELLIDO2,vDIRECCION,vTEL_EMP,vTEL_PER,vSALARIO,vFECHA_NAC,vCENTRO
  FROM TRABAJADOR
  WHERE DNI = vDNI
  ORDER BY DNI;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    RAISE_APPLICATION_ERROR(-20015 , 'No existe un trabajador con ese DNI' );
  WHEN TOO_MANY_ROWS THEN
    RAISE_APPLICATION_ERROR(-20013, 'Se han encontrado más valores de los esperados');
END;