CREATE OR REPLACE PROCEDURE LECTURA_TRABAJADORES_DNI
(DNI IN TRABAJADOR.DNI%TYPE, vDNI OUT TRABAJADOR.DNI%TYPE,
 NOMBRE IN TRABAJADOR.NOMBRE%TYPE, vNOMBRE OUT TRABAJADOR.NOMBRE%TYPE,
 APELLIDO1 IN TRABAJADOR.APELLIDO1%TYPE, vAPELLIDO1 OUT TRABAJADOR.APELLIDO1%TYPE,
 APELLIDO2 IN TRABAJADOR.APELLIDO2%TYPE, vAPELLIDO2 OUT TRABAJADOR.APELLIDO2%TYPE,
 DIRECCION IN TRABAJADOR.DIRECCION%TYPE, vDIRECCION OUT TRABAJADOR.DIRECCION%TYPE,
 TEL_EMP IN TRABAJADOR.TEL_EMP%TYPE, vTEL_EMP OUT TRABAJADOR.TEL_EMP%TYPE,
 TEL_PER IN TRABAJADOR.TEL_PER%TYPE, vTEL_PER OUT TRABAJADOR.TEL_PER%TYPE,
 SALARIO IN TRABAJADOR.SALARIO%TYPE, vSALARIO OUT TRABAJADOR.SALARIO%TYPE,
 FECHA_NAC IN TRABAJADOR.FECHA_NAC%TYPE, vFECHA_NAC OUT TRABAJADOR.FECHA_NAC%TYPE,
 TIPO IN TRABAJADOR.TIPO%TYPE, vTIPO OUT TRABAJADOR.TIPO%TYPE,
 CENTRO IN TRABAJADOR.CENTRO%TYPE, vCENTRO OUT TRABAJADOR.CENTRO%TYPE
)
IS  
BEGIN 
  SELECT DNI,NOMBRE,APELLIDO1,APELLIDO2,DIRECCION,TEL_EMP,TEL_PER,SALARIO,FECHA_NAC,TIPO,CENTRO
  INTO vDNI,vNOMBRE,vAPELLIDO1,vAPELLIDO2,vDIRECCION,vTEL_EMP,vTEL_PER,vSALARIO,vFECHA_NAC,vTIPO,vCENTRO
  FROM TRABAJADOR
  WHERE DNI = vDNI
  ORDER BY DNI;
  
END;